WIP - overriding listing tags
pantheon-systems/pantheon_advanced_page_cache pull request #30
Opened 2020-05-16 00:51 UTC by stevector

https://www.drupal.org/project/pantheon_advanced_page_cache/issues/2944229

2020-08-26 13:45 UTC, clayfreeman requested changes
I've attached a review covering current general best practice for adding new constructor arguments for dependency injection. I've also added feedback on code style in a couple places.

Let me know what you think! I'm excited to get this change in, especially with https://www.drupal.org/node/3107058 having been merged into Drupal core.

2020-08-26 13:45 UTC, clayfreeman commented on src/EventSubscriber/CacheableResponseSubscriber.php
> +  public function __construct(LoggerInterface $logger, ConfigFactory $configFactory) {
This is the standard way of handling new constructor arguments:

```suggestion
  public function __construct(LoggerInterface $logger, ConfigFactoryInterface $config_factory = NULL) {
    if (!$config_factory instanceof ConfigFactoryInterface) {
      @trigger_error('Not passing the config factory service as the second parameter to ' . __METHOD__ . ' is deprecated in pantheon_advanced_page_cache:1.1.0 and will throw a type error in pantheon_advanced_page_cache:2.0.0. Pass an instance of \\Drupal\\Core\\Config\\ConfigFactoryInterface. See https://www.drupal.org/node/2944229', E_USER_DEPRECATED);
      $config_factory = \Drupal::service('config.factory');
    }
```

2020-08-26 13:45 UTC, clayfreeman commented on src/EventSubscriber/CacheableResponseSubscriber.php
> +    $this->configFactory = $configFactory;
This change was made in compliance with Drupal coding standards. Local variables use underscores, not camel case.

```suggestion
    $this->configFactory = $config_factory;
```

2020-08-26 13:45 UTC, clayfreeman commented on src/EventSubscriber/CacheableResponseSubscriber.php
> +   * @param \Drupal\Core\Config\ConfigFactory $configFactory
You should really use the interface instead:

```suggestion
   * @param \Drupal\Core\Config\ConfigFactoryInterface $config_factory
```

2020-08-26 13:45 UTC, clayfreeman commented on src/EventSubscriber/CacheableResponseSubscriber.php
> +use Drupal\Core\Config\ConfigFactory;
```suggestion
use Drupal\Core\Config\ConfigFactoryInterface;
```

2020-08-26 13:45 UTC, clayfreeman commented on src/EventSubscriber/CacheableResponseSubscriber.php
> +   * @var \Drupal\Core\Config\ConfigFactory
```suggestion
   * @var \Drupal\Core\Config\ConfigFactoryInterface
```

2020-08-26 13:45 UTC, clayfreeman commented on src/EventSubscriber/CacheableResponseSubscriber.php
> +    }
This is simpler to read, imo.

```suggestion
    return TRUE;
```

2020-08-26 13:51 UTC, clayfreeman commented
Also, you may want to test whether your update is being applied correctly; I believe you should be using a post update hook if manipulating higher-level Drupal constructs such as configuration defaults.

2020-08-26 13:59 UTC, clayfreeman commented on README.md
> +Sites that installed this module prior to 1.1 should uninstall and reinstall or run this command to update their settings.
```suggestion
Prior to the 1.2 release, this module would change the cache tags used on default listings.
This changing of was done to make cache hits more likely but resulted in [confusing cache clearing behavior](https://www.drupal.org/project/pantheon_advanced_page_cache/issues/2944229).
Sites that installed this module prior to 1.2 should uninstall and reinstall or run this command to update their settings.
```

2020-08-26 14:00 UTC, clayfreeman commented on README.md
> +Sites that installed this module prior to 1.1 should uninstall and reinstall or run this command to update their settings.
You may wish to ignore this specific suggestion; I was going by [your comment on Drupal.org](https://www.drupal.org/project/pantheon_advanced_page_cache/issues/2944229#comment-13623674).

2021-01-04 20:00 UTC, stevector commented
Thanks @clayfreeman !

2021-01-04 20:00 UTC, merged