Fixes missing schema for pantheon_advanced_page_cache.settings
pantheon-systems/pantheon_advanced_page_cache pull request #32
Opened 2021-02-16 21:42 UTC by davereid-pfg

Resolves https://www.drupal.org/project/pantheon_advanced_page_cache/issues/3194124

2021-03-08 21:42 UTC, clayfreeman requested changes

2021-03-08 21:42 UTC, clayfreeman commented on config/schema/pantheon_advanced_page_cache.schema.yml
> +  type: config_entity
This should be `type: mapping`, no?

2021-03-09 15:21 UTC, davereid-pfg commented on config/schema/pantheon_advanced_page_cache.schema.yml
> +  type: config_entity
Yup, you're right!

2021-03-09 15:49 UTC, clayfreeman approved these changes

2021-09-03 18:38 UTC, dpagini commented
👍 I'd also like to see this move forward and be added to the module.

2022-04-25 22:24 UTC, kporras07 commented
Looks good. Thanks!

2022-04-25 22:24 UTC, kporras07 commented
Looks good. Thanks!

2022-04-25 22:24 UTC, merged

2022-07-26 16:27 UTC, davereid-pfg commented
Any chance we could possibly get an updated release of the module @kporras07?

2022-07-26 22:02 UTC, kporras07 commented
@davereid-pfg https://www.drupal.org/project/pantheon_advanced_page_cache/releases/8.x-1.3 just created. Thanks!